name: libra_scan
description: "Project Skripsi library scanning menggunakan Barcode pada buku"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  mobile_scanner: ^7.0.0
  fl_chart: ^1.0.0
  pdf: ^3.10.4
  printing: ^5.12.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  fluttertoast: ^8.2.8
  animated_snack_bar: ^0.4.0
  barcode_widget: ^2.0.4

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/takologic.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/lottie/
    - asset/about/
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg

#  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700