// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJy_AnKjg-4MV8jnC3r1qGfZRF5ch52Zs',
    appId: '1:10237643625:web:2ba53b8a341efbcf840bf8',
    messagingSenderId: '10237643625',
    projectId: 'librascan-7daa0',
    authDomain: 'librascan-7daa0.firebaseapp.com',
    databaseURL: 'https://librascan-7daa0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librascan-7daa0.firebasestorage.app',
    measurementId: 'G-HJ9NPR44WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_PYyrCEnzLUvKeXhq1iAw_vWty8dzmg',
    appId: '1:10237643625:android:d692c78bf3868861840bf8',
    messagingSenderId: '10237643625',
    projectId: 'librascan-7daa0',
    databaseURL: 'https://librascan-7daa0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librascan-7daa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGineEx7psXTwJ-qXEulPtMHDPaOMv2k8',
    appId: '1:10237643625:ios:d4a4fa670fe1af93840bf8',
    messagingSenderId: '10237643625',
    projectId: 'librascan-7daa0',
    databaseURL: 'https://librascan-7daa0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librascan-7daa0.firebasestorage.app',
    iosBundleId: 'com.mhmdnurulkarim.librascan.libraScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJy_AnKjg-4MV8jnC3r1qGfZRF5ch52Zs',
    appId: '1:10237643625:web:561f8776d9d8afe0840bf8',
    messagingSenderId: '10237643625',
    projectId: 'librascan-7daa0',
    authDomain: 'librascan-7daa0.firebaseapp.com',
    databaseURL: 'https://librascan-7daa0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'librascan-7daa0.firebasestorage.app',
    measurementId: 'G-MG5ECYNJCY',
  );
}
