name: Flutter Android CI & Release

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter --version
      - run: flutter pub get

      - name: Build Release APK
        run: |
          mkdir -p build/symbols/${{ github.ref_name }}
          flutter build apk \
            --release \
            --tree-shake-icons \
            --obfuscate \
            --split-debug-info=build/symbols/${{ github.ref_name }}

      - name: Rename APK with tag
        run: |
          TAG="${{ github.ref_name }}"
          mkdir -p dist
          cp build/app/outputs/flutter-apk/app-release.apk "dist/LibraScan_${TAG}.apk"
          echo "RENAMED_APK=dist/LibraScan_${TAG}.apk" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            ${{ env.RENAMED_APK }}
            build/symbols/${{ github.ref_name }}/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: dist

      - name: List files for debug
        run: ls -lh dist || true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "LibraScan ${{ github.ref_name }}"
          files: |
            dist/LibraScan_${{ github.ref_name }}.apk
            dist/*.symbols
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
